name: "Create release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  create-new-release:
    name: "Create new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: startsWith(github.ref, 'refs/tags/') && ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # scottbrenner
          # tag_name: ${{ github.ref }}
          # release_name: Release ${{ github.ref }}
          # body: |
          #   ${{ steps.Changelog.outputs.changelog }}
          # draft: false
          # prerelease: false
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: publish
        run: yarn publish-pkg
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}