# This workflow will run tests using node whenever a commit is pushed to develop or main
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: Stable branch Continuous Integration

on:
  push:
    # List all branches that shall be tested and are not protected by requiring pull requests to commit to.
    branches:
      - "develop"
      - "main"

jobs:
  dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_distribution: ["temurin"]
        jdk_version: ["8.0.332+9"]
        node_version: ["16"]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install YARN dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Set up JDK for Maven Deployment 
        uses: actions/setup-java@v3
        with:
          cache: maven
          java-version: ${{ matrix.jdk_version }}
          distribution: ${{ matrix.jdk_distribution }}
          server-id: "ossrh" 
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}

      - name: Install MAVEN dependencies
        run: mvn -B process-resources

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build

      - name: E2E tests
        run: yarn test:e2e
