# This workflow will run tests using node whenever a commit is pushed to develop or main
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: Stable branch Continuous Integration

on:
  push:
    # List all branches that shall be tested and are not protected by requiring pull requests to commit to.
    branches:
      - "develop"
      - "main"

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install
        run: yarn install --frozen-lockfile

      - name: test
        run: yarn test

      - name: build
        run: yarn build
