# This workflow will run the distribution steps using node when a pull request is created or updated
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: PR Echo 

on:
  pull_request:
    branches: [develop]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Action ${{github.event.pull_request.action}} on obj ${{toJSON(github.event.pull_request)}} and ${{github.event.action}}"
      - name: checkout
        uses: actions/checkout@v3
      - name: Echo 2
        if: github.event.action == 'synchronize'
        uses: ./.github/actions/slack-webhook-action #tiloio/slack-webhook-action@v1.1.2
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "{{GITHUB_ACTOR}} opened pull request {{CUSTOM_COMMIT_MSG}} on repository {{GITHUB_REF}}",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> opened pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'
