# This workflow will run the distribution steps using node when a pull request is created or updated
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: PR Continuous Integration 

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: install
        run: yarn install --frozen-lockfile

      - name: test
        run: yarn test

      - name: build
        run: yarn build
