# This workflow will run the distribution steps using node when a pull request is created or updated
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: PR Slack Communication

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: [develop]
  pull_request_review:
    types: [submitted,dismissed]  
    branches: [develop]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: PR opened
        if: github.event.action == 'opened'
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> opened pull request {{CUSTOM_COMMIT_MESSAGE}} on repository {{GITHUB_REF}}",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> opened pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'

      - name: PR opened
        if: github.event.action == 'reopened'
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> reopened  pull request {{CUSTOM_COMMIT_MESSAGE}} on repository {{GITHUB_REF}}",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> reopened pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'


      - name: PR closed
        if: github.event.action == 'closed' && github.event.pull_request.merged != true
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> closed pull request {{CUSTOM_COMMIT_MESSAGE}} on repository {{GITHUB_REF}}",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> closed pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'


      - name: PR merged 
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> merged pull request {{CUSTOM_COMMIT_MESSAGE}}",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "<{{CUSTOM_AUTHOR_LINK}}|{{GITHUB_ACTOR}}> merged pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'

      - name: PR approved 
        if: github.event.action == 'submitted'
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "Pull request {{CUSTOM_COMMIT_MESSAGE}} approved",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "Pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_ was approved",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'
      - name: PR dismissed 
        if: github.event.action == 'dismissed'
        uses: dreamora/slack-webhook-action@v1.0.3
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_CHANNEL_URL }}
          slack_json:
           '{
              "username": "{{GITHUB_ACTOR}}",
              "text": "Pull request {{CUSTOM_COMMIT_MESSAGE}} dismissed",
              "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      {
                        "type": "mrkdwn",
                        "text": "Pull request _<{{CUSTOM_COMMIT_URL}}|{{CUSTOM_PR_TITLE}}>_ was approved",
                      },
                  },
                  {
                    "type": "context",
                    "elements":
                      [
                        {
                          "type": "mrkdwn",
                          "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>",
                        },
                      ],
                  },
                ],
            }'
